### ISSUE TITLE
Support TLS for HTTP server

### ISSUE THREAD

**Issue by psFried** [psFried/roperator#28]
Currently, roperator will spin up an HTTP server to serve prometheus metrics and to expose a health check endpoint. This is all done over plain HTTP only, and only the port is configurable, unless you want to disable the endpoints entirely. 

We want to add optional TLS support for these endpoints, which will require some additional configuration options. In particular, we'll need 

- a way to specify the TLS certificate to use
- Whether to also listen on regular http, have regular http redirect to https, or to disable http altogether
- I don't think there's anything else that really needs to be configurable, but please chime in if there's something else you think might be good.

TLS may seem unnecessary for just metrics and a health check, but the ultimate goal is to make it easy for an operator to also support acting as a [Validating Admission Webhook](https://v1-15.docs.kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/), though we'll have a separate issue for that particular feature.

**Comment by pms1969** [comment]
Would it not be best to just use a sidecar for such functionality.  Separates the concern, and allows for choices in this space (linkerd, istio)

**Comment by psFried** [comment]
@pms1969 Yeah that's a good point. At a minimum, that would make this extremely low priority. I'll go ahead and just close this issue for now. Anyone else, feel free to open a new issue if you have a use case that isn't satisfied by using a sidecar to terminate TLS.
