### ISSUE TITLE
Non-namespaced parents should be able to have namespaced children

### ISSUE THREAD

**Issue by asthasr** [psFried/roperator#8]
I am working on a CRD operator that is running afoul of the namespace constraint. The [stated aim](https://github.com/psFried/roperator/blob/71af1cce1be583d4c17db072bcb628f8d6bb78a5/src/runner/reconcile/sync.rs#L174) of the constraint is to prevent the complexity of having namespaced parents with non-namespaced children. That's not what I'm doing; my CRD (not namespaced) creates a namespace and then a resource within that namespace. The second child resource runs afoul of the constraint.

This error also contradicts the [docs](https://github.com/psFried/roperator/blob/6f40213a2bd938450a6a213e83f5b8c613e46daf/docs/guide/handler-sync.md#sync-function-best-practices-and-details), which say:

> If you need resources that span multiple namespaces, then you should use a non-namespaced (a.k.a. Cluster Scoped) parent CRD.

**Comment by psFried** [comment]
Thanks a lot for the contribution! This was one of those things that I just hadn't thought about, but it seems like it's worth supporting this use case. I'll have a look at the PR and we can see about doing a point release, since this shouldn't be a breaking change.

**Comment by psFried** [comment]
One thought did cross my mind about this. When you want the operator to create a namespace and then resources within that namespace, you need to of course create the namespace before the resources within it.  Your handler would have to first return a syncResponse with _only_ then namespace resource, and then create the rest of the child resources later, after the namespace shows up in the syncRequest children. This type of thing would probably make an excellent example. I'll try to create a basic example that shows how to do that, since it's likely that others would benefit from it as well.

**Comment by asthasr** [comment]
So, that explains why it was failing on the first request and then succeeding on the second. It makes sense, but I had been thinking of it as equivalent to applying a YAML manifest, which obviously is higher level than this.

I have implemented the logic you suggest, and it seems to work pretty well:

```rust
/// Encapsulates the creation of the child objects (e.g., `Namespace` and `Rolebinding`) and
/// returns a list of opaque JSON objects for syncing. Note that it returns only the namespace if a
/// namespace is not included in the `SyncRequest`, and then creates a `RoleBinding` in a
/// subsequent request.
pub fn create_child_objects(request: &SyncRequest) -> anyhow::Result<Vec<Value>> {
    let parent: DevSandbox = request.deserialize_parent()?;
    let mut children: Vec<Value> = Vec::new();
    let names = Names::new(&parent)?;
    let ns = create_namespace(&names).map(serde_json::to_value)??;
    children.push(ns);
    if request.has_child("v1", "Namespace", "", &names.namespace) {
        info!("Namespace exists; creating rolebinding");
        let rb = create_rolebinding(&names).map(serde_json::to_value)??;
        children.push(rb);
    } else {
        info!("Namespace does not exist; creating it");
    }
    Ok(children)
}
```

It strikes me as a little odd that there's no way to check whether something exists using one of the JSON objects. What if you could use a method like `request.has_child_value()` to check for a child with a given serializable JSON object?
